from pathlib import Path
import json
P=Path(__file__).resolve().parents[1]
rows=json.loads((P/'RESULTATS.json').read_text());R={r['name']:r for r in rows}
def status(n):return R.get(n,{}).get('status','NT')
def link(n):return f'[{n}](logs/{n}.log)'
def short(n):
 r=R.get(n,{})
 return f"{status(n)} ; {r.get('distinct','NP')} distincts ; {r.get('seconds','NP')} s"
mutations=[('Cliché sur pointe','MC_mut_registry_tip_checked',['ARule']),('Suppression du seuil A','MC_mut_registry_no_threshold_checked',['ARule']),('Registre engagé utilisé comme veto','MC_mut_registry_lock_checked',['NoJournalVeto']),('H1 promoteur','MC_mut_h1_promote_checked',['H1Subset']),('H1 limité à l’adoptée','MC_mut_h1_adopted_only_checked',['H1Order','H1NonVacuity','NoContinuation']),('MAINTAIN saute H1','MC_mut_h1_maintain_checked',['H1Order','H1NonVacuity','NoContinuation']),('Deep dépend d’une ancre locale','MC_mut_h1_anchor_deep_checked',['H1Order','H1Orientation']),('Frein annule tous les budgets','MC_mut_brake_checked',['Mechanical']),('ADD efface le passif','MC_mut_add_checked',['AddNoReset']),('Ancre libre à la pointe','MC_mut_free_anchor_checked',['AnchorExact']),('Scellement oublié','MC_mut_forget_seal_checked',['G0']),('Réservation par génération','MC_mut_generation_checked',['S1']),('Import non idempotent','MC_mut_import_checked',['MON1','MON2','MON3','MON4'])]
matched=sum(status(n)=='FAIL' and R[n]['exit']==12 and bool(set(R[n]['violations'])&set(expected)) for _,n,expected in mutations)
fast=[f'MC_fast_on_{v}' for v in ['00','01','10','11']]
mirror_pass=all(status(n)=='PASS' and R[n]['queue']==0 for n in fast)
mirror_off=all(status(f'MC_fast_off_{v}')=='FAIL' and R[f'MC_fast_off_{v}']['violations']==['RegistryImmutable'] for v in ['00','01','10','11'])
h1=[f'MC_h1_{s}_checked' for s in ['forward','forward_k2','inverse','mutual','foreign','false','losers','shallow','stale']]
s=[]
s.append('# Rapport TLA+ — N-SPEC v0.6\n\n30 septembre 2026. Exécution de `MANDAT-TLA-v0.6.md`, §8 prioritaire. Sources normatives et modèles v0.5 conservés ; aucune commande Git.\n')
s.append('## Résultat et décision de qualification\n')
s.append(f"Le miroir élargi final est **{'PASS borné pour le fort historique et le moniteur C6 local' if mirror_pass else 'NON QUALIFIÉ : voir statuts par vecteur'}** avec A activée. A désactivée : **{'le FAIL historique est retrouvé sur les quatre vecteurs' if mirror_off else 'voir résultats, contrôle non entièrement acquis'}**. Les premières explorations interrompues restent INCOMPLET ; elles ne sont pas converties en PASS.\n")
s.append(f"A activée, les quatre vecteurs finaux donnent **{sum(status(n)=='PASS' for n in fast)} PASS, {sum(status(n)=='INCOMPLET' for n in fast)} INCOMPLET, {sum(status(n)=='FAIL' for n in fast)} FAIL**. L’interruption d’un seul vecteur suffit à empêcher un PASS composé.\n")
s.append(f"Les {len(h1)} scénarios d’ordre H1 corrigés donnent {sum(status(n)=='PASS' for n in h1)} PASS bornés. Sensibilité : **{matched}/13 mutations** réfutées par un moniteur attendu, avec code TLC 12. Voie lente : {status('MC_brake_slow_checked')} ; témoin de sortie après libération de quota : {status('MC_witness_brake_Release_checked')}.\n")
s.append('**Gel bloqué.** CP_reg et A4 ne sont pas qualifiés sous un domaine H_N propre à N. Des contre-exemples bornés sont publiés. Les familles de modèles ne sont pas composées en un modèle global ; plusieurs obligations restent NT, en particulier le contrôle complet, la vivacité générale et l’application monétaire complète. La livraison n’est donc pas une qualification intégrale du mandat.\n')
s.append('## 1. Miroir de la règle A — §8.1\n\nMême générateur élargi que v0.5 : deux honnêtes, un adversaire, poids `(2,1,1)`, deux branches, trois époques, deux slots par époque, slots 0–5, KReg=1, maxreorg=registry_min_blocks=4, divergence autorisée dès 0. Seul `RuleA` diffère dans chaque paire finale. La nouvelle maturité est réduite au début de l’époque : cette restriction est explicitement compensée par les sondes de fenêtre et de fermeture, sans prétendre composer leurs résultats.\n')
s.append('| Bitcoin | A désactivée : fort | A activée : fort + C6 | Distincts A on | File publiée |\n|---|---|---|---:|---:|')
for v in ['00','01','10','11']:
 a=f'MC_fast_off_{v}';b=f'MC_fast_on_{v}';r=R.get(b,{})
 s.append(f'| (0,{v[0]},{v[1]}) | {link(a)} : {status(a)} | {link(b)} : {status(b)} | {r.get("distinct","NP")} | {r.get("queue","NP")} |')
s.append('\nLa composition est exhaustive uniquement si les quatre lignes A on terminent avec file vide : Init impose bitcoin[0]=0, les deux autres composantes valent 0 ou 1, et Next ne modifie jamais Bitcoin dans cette famille. Les quatre états d’entrée sont disjoints et leur union est exactement Init. Pour un INCOMPLET, les compteurs du tableau sont ceux du dernier point publié, pas une file finale épuisée. Aucun filtrage de densité, contrainte d’état, symétrie ou limite de profondeur ne retire une histoire.\n')
if mirror_pass:s.append(f"Cette union couvre **{sum(R[n]['distinct'] for n in fast):,} états distincts** ; chaque composante est terminée séparément. Ce PASS du vieux moniteur local ne vaut pas PASS CP_reg global.\n")
s.append('| Replay historique | A désactivée | A activée |\n|---|---|---|')
for tag in ['spec','spec_adopt']:
 a=f'MC_v6_replay_{tag}_off';b=f'MC_v6_replay_{tag}_on'
 s.append(f'| {tag} | {link(a)} : {short(a)} | {link(b)} : {short(b)} |')
s.append('\nLe replay signature conserve maxreorg=4 et EndSlot=5 ; celui d’adoption conserve maxreorg=1 et EndSlot=4. Les parcours attendus sont respectivement 9 et 13 états. Un PASS de replay ne prouve que ce parcours. Le témoin '+link('MC_witness_mirror_advance')+' donne '+status('MC_witness_mirror_advance')+' : A avance réellement le support. '+link('MC_witness_mirror_empty')+' donne '+status('MC_witness_mirror_empty')+' après deux époques entièrement vides.\n')
s.append('`RegistryModelV6` implémente la fermeture sur l’en-tête candidat, l’héritage, le compte inclusif et le maintien du registre déjà installé tant que la fenêtre est ouverte. `RegistryModelFast2` calcule la même fonction plus directement dans la projection ADD. Les sondes d’équivalence 1/2/4, la justification algébrique et les versions intermédiaires sont décrites dans [PORTEE-ET-MAPPING.md](PORTEE-ET-MAPPING.md). L’ancien invariant fort demeure inchangé ; C6 ne le remplace pas.\n')
s.append('### C6 sur la sonde générale — moniteur local séparé du fort\n\nLes recherches regroupées à seuil 1 et 2 ont été interrompues au plafond : elles restent INCOMPLET. Les partitions suivantes gardent le même Init/Next et fixent seulement les deux composantes Bitcoin invariantes. Leur union couvre exactement les quatre entrées initiales. Aucune prémisse CP_reg ne filtre les histoires.\n')
s.append('| Seuil | (0,0,0) | (0,0,1) | (0,1,0) | (0,1,1) | Composition |\n|---|---|---|---|---|---|')
for k in [1,2]:
 names=[f'MC_c6_k{k}_{v}' for v in ['00','01','10','11']]
 done=all(status(n)=='PASS' and R[n]['queue']==0 for n in names)
 s.append('| '+str(k)+' | '+' | '.join(link(n)+' : '+status(n) for n in names)+' | '+('PASS borné C6 — '+str(sum(R[n]['distinct'] for n in names))+' états' if done else 'INCOMPLET / non acquis')+' |')
s.append('\nDans le miroir et ces partitions, `RegistryStableOnCommonPrefix` compare directement les registres des engagements locaux successifs à supports égaux ; il ne conserve pas toutes les anciennes époques. Les sondes `RegistryCommitmentsChecked` et le journal persistant `RegistryAudit` comparent en plus la projection ADD du contrôle et le calendrier dérivé, entre nœuds et engagements conservés, sans modifier les actions de production/adoption. Le contrôle complet de la SPEC reste NT.\n')
s.append('## 2. H1 — §8.2\n\n`H1OrdersChecked` explore toutes les permutations unitaires des six événements C/W/L/BTC/F/A par nœud, leurs entrelacements et les livraisons groupées simultanées. Les états peuvent être fusionnés par TLC quand toutes les données et l’état d’adoption pertinent coïncident : aucun ordre n’est exclu. C est supérieure, W inférieure, et L fournit une troisième branche.\n')
s.append('| Scénario | Résultat |\n|---|---|')
for n in h1:s.append(f'| {link(n)} | {short(n)} |')
s.append('\nLes invariants comparent le résultat H1 quand les données reçues sont identiques et exigent `AdoptedWithH1 ⊆ AdoptableByBaseN`. Les témoins CommonVeto, Maintain et Unknown sont séparés des PASS. Les mutations vérifient notamment la prise en compte d’une perdante jamais adoptée, MAINTAIN et l’indépendance de Deep vis-à-vis de l’ancre. Les motifs d’ancre/BTC de la base N sont testés séparément ; leur composition avec H1 reste NT et aucune sûreté sous éclipse n’en est déduite.\n')
s.append('`H1Scan` distingue références étrangères, dossiers pertinents manquants, fenêtres mûres, étapes strictes de progrès et scan complet. `H1Reevaluation` conserve le motif de base pendant un veto, réévalue sur rang et Bitcoin et conserve l’archive lors d’une éviction. Le contre-exemple de cadence avec anciennes références est publié ci-dessous.\n')
s.append('## 3. Frein mécanique — §8.3\n\nCalendrier réduit L=5, vingt époques, cinq producteurs, W=1000. L’identité 1 est présente à 2/3, les autres sont silencieuses ; l’identité 5 a un auto-ommer au slot 44, sans crédit d’activité mais bloquant son éligibilité lente. Activité, suspicion, file et récupérations sont rejouées avant santé ; le masque Q est fixe. Les quotas 2 %/époque, 5 %/sept époques et 1 % lent/sept époques sont entiers et prospectifs.\n')
s.append('| Époque | W_f | Budget lent | Exclusion | Rotation |\n|---:|---:|---:|---|---|\n| 10 | 1000 | 10 | IID 4, poids 5 | exécutée sous frein |\n| 11–16 | 995 | 4 | aucun lot supplémentaire admissible | sans condition de santé |\n| 17 | 995 | 9 | IID 5, poids 5 | déjà effectuée |\n')
s.append('Ce tableau est le calcul de référence de [tools/brake_reference.py](tools/brake_reference.py), à confronter aux témoins TLC : '+link('MC_witness_brake_Slow_checked')+' = '+status('MC_witness_brake_Slow_checked')+', '+link('MC_witness_brake_Release_checked')+' = '+status('MC_witness_brake_Release_checked')+'. La propriété temporelle sous WF(Advance) donne '+status('MC_brake_live_checked')+' en formulation directe, et '+status('MC_brake_live_mechanical')+' avec la formulation équivalente par avancement d’époque. Elle ne démontre pas une reprise productive infinie.\n')
s.append('Aucune appréciation locale n’intervient une fois calendrier, support et observations fixés. La SPEC impose cette mécanique. Les arrondis W<100, les identités indivisibles trop lourdes et l’absence persistante d’avancement de support restent des blocages intentionnels. La sonde pondérée 0,68 est distincte du calendrier cyclique : 680 présents, 120 honnêtes disparus, 200 adverses abstinents ; le masque QUEUED retire ces derniers de la mesure de santé sans confondre santé et livraison.\n')
s.append('## 4. Contre-exemples et séparation des garanties\n\n| Recherche | Résultat final | Interprétation |\n|---|---|---|')
for n,why in [('MC_general_a_k1_strong','Contre-exemple avec productions de la loterie abstraite, A active, maxreorg=1.'),('MC_general_a_k2_strong','Même défaut à maxreorg=2, sans déconnexion excessive.'),('MC_audit_cp_k1','Journal persistant des engagements honnêtes : CP_reg séparé.'),('MC_audit_cp_k2','Journal persistant, seuil 2.'),('MC_replay_audit_c6','C6 sur le même parcours qui viole le fort et CP_reg.'),('MC_registry_commits_CPreg_checked','D_e diffère malgré même contexte ; obligation A3 non acquise.'),('MC_registry_commits_RegistryImmutable_checked','La règle A n’assure pas une immutabilité globale inconditionnelle.'),('MC_registry_commits_C6_checked','Lemme conditionnel séparé ; aucun filtre CP_reg.'),('MC_anchor_agreement_checked','Ancres incompatibles après livraisons séparées, sans domaine réseau qualifié.'),('MC_tie_reservations','Convergence des données n’efface pas des réservations antérieures différentes.'),('MC_scan_stale_counterexample','La fréquence des empreintes seule ne borne pas la fraîcheur du progrès.')]:
 s.append(f'| {link(n)} | {status(n)} | {why} |')
s.append('\nContre-exemples issus du générateur de production, sans mutation : '+link('MC_replay_general_k1')+' et '+link('MC_replay_general_k2')+'. Un bloc B_0 porte un ADD pour le producteur 2. Au slot 4, le nœud 1 signe C_4 avec `(2,1,1)` ; le nœud 2 signe B_4 avec `(2,2,1)` après fermeture de la fenêtre. Le nœud 1 reçoit ensuite cette branche supérieure et installe le second registre, dans la même époque et le même contexte. Au seuil 2, B_3 fournit le bloc comptable supplémentaire. La pointe adoptée antérieure du nœud 1 est genesis : **zéro déconnexion**, donc aucun STOP profond attendu. Même la branche du seul bloc C_4 signé ne représenterait qu’une déconnexion. La règle A est respectée sur chaque branche ; la propriété forte demeure trop forte sans CP_reg.\n')
s.append('Le journal global trouve CP_reg en '+str(R.get('MC_audit_cp_k1',{}).get('depth','NP'))+' états au seuil 1 et '+str(R.get('MC_audit_cp_k2',{}).get('depth','NP'))+' au seuil 2, sur leurs vecteurs Bitcoin fixes. Au seuil 1, la partition reste active : deux signatures honnêtes de l’époque 2 portent des D_e différents, et des registres `(2,1,1)` / `(2,2,1)`. Le moniteur local fort est encore vrai à ce point ; aucune déconnexion ni réunion n’est requise pour ce FAIL global. Le replay court '+link('MC_replay_audit_min_k1')+' donne '+status('MC_replay_audit_min_k1')+'. Le domaine réseau non borné est annoncé avant la recherche ; aucune hypothèse corrective n’est introduite après coup.\n')
s.append('Recherche BFS à un worker : '+link('MC_min_general_k1')+' = '+status('MC_min_general_k1')+' (profondeur '+str(R.get('MC_min_general_k1',{}).get('depth','NP'))+'), '+link('MC_min_general_k2')+' = '+status('MC_min_general_k2')+' (profondeur '+str(R.get('MC_min_general_k2',{}).get('depth','NP'))+'). Les replays imposés des premières traces contiennent respectivement 13 et 14 états ; la minimalité BFS porte uniquement sur ces bornes et ce générateur, sous la réserve habituelle des fingerprints TLC.\n')
s.append('\nLe replay de fermeture '+link('MC_replay_closure_checked_fixed')+' compare `⟨0,11,13⟩` à `⟨0,23⟩`. Le bloc 0 est commun et seul antérieur à la coupure 1 ; les comptes jusqu’au porteur au slot 3 sont 2 et 1. Au seuil 2, le registre passe de `(3,1,1)` à `(2,1,1)`. Le LCA a hauteur 1 : **deux déconnexions, égales à maxreorg=2**, donc ce n’est pas un cas exigeant >maxreorg. L’ancre éventuelle au bloc commun n’empêche pas ce changement de compte. Les fixtures sont déclarées validées, mais cette sonde ne vérifie ni la loterie ni Rank : son passage de longueur 3 à longueur 2 ne démontre donc pas une adoption conforme à BaseNDecision. Il illustre le changement de fermeture et sa distance. Les contre-exemples issus des productions ci-dessus, indépendants de cette fixture, interdisent de généraliser le PASS du miroir.\n')
s.append('Le replay '+link('MC_replay_anchor_split_checked_fixed')+' adopte A chez le nœud 1 et B chez le nœud 2, chacune de hauteur 3. Les bornes N/BTC autorisent une ancre de hauteur 2 de chaque côté. Elles sont incompatibles. La première hypothèse manquante est une borne réseau sur l’histoire de construction et de livraison, pas seulement après réunion. La SPEC n’est ni modifiée ni complétée par un verrou pour cacher ce résultat.\n')
s.append('## 5. Mutations négatives\n\n| Mutation | Moniteur attendu | Résultat observé |\n|---|---|---|')
for label,n,expected in mutations:
 r=R.get(n,{})
 s.append(f'| {label} | {", ".join(expected)} | {link(n)} : {status(n)} — {", ".join(r.get("violations",[])) or "aucune violation publiée"} |')
s.append('\nAucune mutation n’est active dans les configurations conformes. Un PASS de mutation serait une absence de sensibilité, jamais un succès. Les premiers essais dont l’audit devenait une garde sont conservés, marqués développement, et ne sont pas comptés dans les 13 contrôles.\n')
s.append('## 6. Outils, exécution et limites\n\nJava fourni : OpenJDK Homebrew 21.0.12.1 ; TLC 2.19 du 8 août 2024, révision 5a47802. JAR copié depuis `modele-v0.5/tla2tools.jar`, lanceur `LocalTLC.java` local sans réseau conservé. Aucun besoin du JAR absent de `etudes/sequenceur/tla/`, ni de téléchargement.\n\nUn verrou de fichier sérialise les explorations. Maximum quatre workers, `-Xmx3g`, BFS, seed 1, répertoire d’états temporaire propre. Le lanceur initial envoyait SIGTERM au plafond de 570 s ; les durées globales peuvent inclure quelques dixièmes de seconde de nettoyage après ce signal. Le lanceur final prend une marge à 569 s et arrête aussi les erreurs fatales de modèle au lieu d’attendre le plafond. Tous les runs interrompus restent INCOMPLET. Les compteurs d’un timeout sont parfois le **dernier point publié**, la file exacte à l’arrêt n’étant pas fournie par TLC.\n\nLe lanceur final fixe aussi le polynôme de fingerprint à `-fp 0` pour les reproductions ; les premiers runs utilisaient l’index choisi par TLC, publié dans leur en-tête. Certains processus Python avaient été mis en attente avant les dernières corrections du lanceur de reproduction : leurs empreintes `run.py` décrivent le fichier sur disque au début du run, pas nécessairement le code Python déjà chargé. La commande Java réellement exécutée, inscrite dans chaque log, fait autorité ; les modèles/configurations et le JAR sont ceux lus pour ce run. Les fingerprints TLC ont un risque résiduel de collision : les estimations publiées par TLC pour chaque PASS restent dans les logs et RESULTATS.json. Elles ne sont pas une epsilon_CP de N. Les runs avec quatre workers ne garantissent pas une trace minimale unique ; les replays explicites donnent des parcours courts reproductibles. Les erreurs syntaxiques, de quantification et d’affectation rencontrées pendant le développement restent des erreurs de modèle/outillage, jamais des FAIL normatifs.\n')
s.append('## 7. Reproduction et dossier de preuve\n\n```sh\ncd etudes/n-spec/tla/modele-v0.6\nTLC_RUN_LABEL=verification ./run.sh MC_fast_off_00 MC_fast_on_00\nTLC_RUN_LABEL=h1 ./run.sh MC_h1_forward_checked\nTLC_RUN_LABEL=frein ./run.sh MC_brake_slow_checked MC_witness_brake_Release_checked\n```\n\nLe contrôle de reproduction `reproduction_check` a retrouvé le FAIL RegistryImmutable attendu en 13 états, avec les logs et la trace d’origine inchangés ; sa validation est dans `logs/reproductions/reproduction_check/VALIDATION.json`. Le label écrit dans un dossier distinct et préserve les logs livrés. Sans label, un run existant est refusé. [RESULTATS-DETAILLES.md](RESULTATS-DETAILLES.md) donne chaque statut, code, compteurs, profondeur, file et durée ; [RESULTATS.json](RESULTATS.json) conserve les configurations exactes et les motifs. Les `.cfg` sont les restrictions exécutables, les logs et [traces/](traces/) les preuves brutes. [PORTEE-ET-MAPPING.md](PORTEE-ET-MAPPING.md) expose les abstractions et H_N ; [COUVERTURE-SONDES.md](COUVERTURE-SONDES.md) inventorie les sondes et NT ; [OBLIGATIONS.md](OBLIGATIONS.md) distingue les moniteurs des obligations complètes, et [TRACES-LECTURE.md](TRACES-LECTURE.md) indexe les contre-exemples. `SHA256.json` et `INTEGRITE-ORIGINAUX.json` identifient les fichiers et contrôlent les copies antérieures.\n')
(P/'RAPPORT-TLA-N-v0.6.md').write_text('\n'.join(s)+'\n')
(P/'MUTATIONS.json').write_text(json.dumps([dict(label=l,name=n,expected=e,status=status(n),observed=R.get(n,{}).get('violations',[]),sensitive=status(n)=='FAIL' and R[n]['exit']==12 and bool(set(R[n]['violations'])&set(e))) for l,n,e in mutations],ensure_ascii=False,indent=2))
print('report written; mutations detected',matched)
